import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { copyFile, mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { once } from 'node:events';

test('Admin authorization, catalog, users, uploads, tickets, orders and JSON persistence', async () => {
  const temporary = await mkdtemp(join(tmpdir(), 'radius-admin-check-'));
  const accountsFile = join(temporary, 'accounts.json');
  await copyFile(new URL('../data/accounts.json', import.meta.url), accountsFile);
  let server;
  const start = async () => {
    server = spawn(process.execPath, ['server.js', '0'], { env: { ...process.env, RADIUS_ACCOUNT_FILE: accountsFile, RADIUS_UPLOAD_DIR: join(temporary, 'uploads') }, cwd: new URL('..', import.meta.url) });
    const [output] = await once(server.stdout, 'data');
    return output.toString().match(/http:\/\/localhost:\d+/)[0].replace('localhost', '127.0.0.1');
  };
  const stop = async () => { const stopped = once(server, 'exit'); server.kill(); await stopped; };
  let base = await start();
  let adminCookie;
  const request = async (path, method = 'GET', data, cookie = adminCookie, extra = {}) => {
    const response = await fetch(base + path, { method, headers: { ...(data ? { 'Content-Type': 'application/json' } : {}), ...(cookie ? { Cookie: cookie } : {}), ...extra }, ...(data ? { body: JSON.stringify(data) } : {}) });
    return { status: response.status, data: await response.json(), cookie: response.headers.get('set-cookie')?.split(';')[0] };
  };
  try {
    assert.equal((await request('/api/admin/data')).status, 401);
    const member = await request('/api/signin', 'POST', { email: 'peter@gmail.com', password: '123' });
    assert.equal((await request('/api/admin/data', 'GET', null, member.cookie)).status, 403);
    assert.equal((await request('/api/admin/products', 'POST', {}, member.cookie)).status, 403);
    const login = await request('/api/signin', 'POST', { email: 'admin@radius.id', password: 'admin123' });
    assert.equal(login.status, 200); assert.equal(login.data.user.role, 'ADMIN'); adminCookie = login.cookie;
    const initial = await request('/api/admin/data');
    assert.equal(initial.status, 200); assert.equal(initial.data.users[0].passwordHash, undefined);
    assert.equal((await request('/data/operations.json')).status, 404);
    assert.equal((await request('/api/admin/products', 'POST', {}, adminCookie, { Origin: 'https://untrusted.test' })).status, 403);
    const escalation = await request('/api/signup', 'POST', { email: 'role-check@example.test', name: 'Role Check', password: '123', role: 'ADMIN' }, null);
    assert.equal(escalation.data.user.role, 'USER');
    assert.equal((await request('/api/admin/data', 'GET', null, escalation.cookie)).status, 403);
    assert.equal((await request('/api/admin/users/radius-admin', 'PATCH', { role: 'USER' })).status, 400);
    assert.equal((await request('/api/admin/users/radius-admin', 'PATCH', { status: 'DISABLED' })).status, 400);
    const upload = await fetch(base + '/api/admin/images', { method: 'POST', headers: { Cookie: adminCookie, 'Content-Type': 'image/jpeg' }, body: await readFile(new URL('../dist/assets/radius-logo.jpg', import.meta.url)) });
    assert.equal(upload.status, 201);
    const { imageUrl } = await upload.json();
    const image = await fetch(base + imageUrl); assert.equal(image.status, 200); assert.equal(image.headers.get('content-type'), 'image/jpeg');
    const fake = await fetch(base + '/api/admin/images', { method: 'POST', headers: { Cookie: adminCookie, 'Content-Type': 'image/jpeg' }, body: '<script>alert(1)</script>' });
    assert.equal(fake.status, 400);
    const svg = await fetch(base + '/api/admin/images', { method: 'POST', headers: { Cookie: adminCookie, 'Content-Type': 'image/svg+xml' }, body: '<svg/>' });
    assert.equal(svg.status, 415);
    const oversized = await fetch(base + '/api/admin/images', { method: 'POST', headers: { Cookie: adminCookie, 'Content-Type': 'image/jpeg' }, body: Buffer.alloc(5 * 1024 * 1024 + 1) });
    assert.equal(oversized.status, 413);
    const productData = { name: 'Test Tee', collection: 'Apparel', price: 100000, stock: 12, imageUrl, description: 'Test description', active: true };
    assert.equal((await request('/api/admin/products', 'POST', { ...productData, price: -1 })).status, 400);
    assert.equal((await request('/api/admin/products', 'POST', { ...productData, imageUrl: 'javascript:alert(1)' })).status, 400);
    const product = await request('/api/admin/products', 'POST', productData); assert.equal(product.status, 201);
    const catalog = await request('/api/catalog'); assert.ok(catalog.data.products.some(item => item.id === product.data.id && item.imageUrl === imageUrl));
    const createdUser = await request('/api/admin/users', 'POST', { name: 'Test Member', email: 'admin-test@example.test', password: '123', role: 'USER', status: 'ACTIVE', membershipPlan: 'YEARLY', membershipRenewalDate: '2027-10-04' });
    assert.equal(createdUser.status, 201); assert.equal(createdUser.data.passwordHash, undefined);
    assert.equal((await request('/api/admin/users', 'POST', { name: 'Duplicate', email: 'ADMIN-TEST@example.test', password: '123' })).status, 409);
    const memberLogin = await request('/api/signin', 'POST', { email: createdUser.data.email, password: '123' }, null);
    const freshAccount = await request('/api/account', 'GET', null, memberLogin.cookie);
    assert.equal(freshAccount.data.membership.interval, 'tahun'); assert.equal(freshAccount.data.membership.price, 999000); assert.deepEqual(freshAccount.data.tickets, []);
    const eventData = { name: 'Test Run', category: 'RUN', city: 'Jakarta', startsAt: '2026-12-10', venue: 'Test venue', distance: '5K', imageUrl, active: true, tickets: [{ name: 'Regular', price: 50000, capacity: 1 }] };
    assert.equal((await request('/api/admin/events', 'POST', { ...eventData, startsAt: '2026-02-30' })).status, 400);
    const event = await request('/api/admin/events', 'POST', eventData); assert.equal(event.status, 201);
    const issue = { customerId: createdUser.data.id, eventId: event.data.id, type: 'Regular' };
    const issued = await Promise.all([request('/api/admin/tickets', 'POST', issue), request('/api/admin/tickets', 'POST', issue)]);
    assert.deepEqual(issued.map(result => result.status).sort(), [201, 409]);
    const ticket = issued.find(result => result.status === 201).data;
    assert.match(ticket.checkInToken, /^[a-f0-9]{64}$/);
    const qrResponse = await fetch(`${base}/api/tickets/${ticket.id}/qr`, { headers: { Cookie: memberLogin.cookie } });
    assert.equal(qrResponse.status, 200); assert.ok(qrResponse.headers.get('content-type').startsWith('image/svg+xml')); assert.match(await qrResponse.text(), /<svg/);
    assert.equal((await fetch(`${base}/api/tickets/${ticket.id}/qr`)).status, 401);
    assert.equal((await fetch(`${base}/api/tickets/${ticket.id}/qr`, { headers: { Cookie: member.cookie } })).status, 404);
    const scan = { eventId: event.data.id, payload: `RADIUS1:${ticket.checkInToken}` };
    assert.equal((await request('/api/admin/check-in', 'POST', scan, memberLogin.cookie)).status, 403);
    assert.equal((await request('/api/admin/check-in', 'POST', { ...scan, eventId: 'wrong-event' })).status, 400);
    assert.equal((await request('/api/admin/check-in', 'POST', { ...scan, payload: 'not-a-radius-qr' })).status, 400);
    assert.equal((await request('/api/admin/check-in', 'POST', { ...scan, payload: `RADIUS1:${'0'.repeat(64)}` })).status, 404);
    assert.equal((await request(`/api/admin/events/${event.data.id}`, 'PATCH', { tickets: [{ name: 'Regular', price: 50000, capacity: 0 }] })).status, 400);
    assert.equal((await request(`/api/admin/events/${event.data.id}`, 'PATCH', { tickets: [{ name: 'Renamed', price: 50000, capacity: 1 }] })).status, 400);
    const editedEvent = await request(`/api/admin/events/${event.data.id}`, 'PATCH', { name: 'Test Run Edited' }); assert.equal(editedEvent.status, 200);
    await request(`/api/admin/events/${event.data.id}`, 'PATCH', { tickets: [{ name: 'Regular', price: 75000, capacity: 1 }] });
    assert.equal((await request('/api/admin/data')).data.tickets.find(item => item.id === ticket.id).price, 50000);
    const scans = await Promise.all([request('/api/admin/check-in', 'POST', scan), request('/api/admin/check-in', 'POST', scan)]);
    assert.deepEqual(scans.map(result => result.status).sort(), [200, 409]);
    const accepted = scans.find(result => result.status === 200).data.ticket;
    assert.equal(accepted.status, 'ATTENDED'); assert.equal(accepted.entryConsumed, true); assert.equal(accepted.checkedInBy, 'radius-admin'); assert.ok(accepted.checkedInAt);
    assert.equal((await request('/api/admin/check-in', 'POST', { ...scan, payload: ticket.code })).status, 409);
    assert.equal((await request(`/api/admin/tickets/${ticket.id}`, 'PATCH', { status: 'VALID' })).status, 409);
    assert.equal((await request(`/api/admin/tickets/${ticket.id}`, 'PATCH', { status: 'CANCELLED' })).status, 409);
    assert.equal((await request(`/api/admin/tickets/${ticket.id}`, 'PATCH', { status: 'ATTENDED' })).status, 409);
    assert.equal((await fetch(`${base}/api/tickets/${ticket.id}/qr`, { headers: { Cookie: memberLogin.cookie } })).status, 409);
    assert.equal((await request('/api/admin/data')).data.tickets.find(item => item.id === ticket.id).checkedInAt, accepted.checkedInAt);
    assert.equal((await request(`/api/admin/tickets/${ticket.id}`, 'DELETE')).status, 405);
    const orderData = { customerId: createdUser.data.id, items: [{ productId: product.data.id, quantity: 2, unitPrice: 1 }], total: 1, status: 'PENDING', address: 'Jl. Radius', notes: 'Internal', tracking: '' };
    const order = await request('/api/admin/orders', 'POST', orderData); assert.equal(order.status, 201); assert.equal(order.data.total, 200000);
    assert.equal((await request('/api/admin/orders', 'POST', { ...orderData, items: [orderData.items[0], orderData.items[0]] })).status, 400);
    await request(`/api/admin/products/${product.data.id}`, 'PATCH', { price: 125000 });
    const shipped = await request(`/api/admin/orders/${order.data.id}`, 'PATCH', { status: 'SHIPPED', tracking: 'RAD123', items: [{ productId: product.data.id, quantity: 3 }] });
    assert.equal(shipped.data.total, 300000); assert.equal(shipped.data.tracking, 'RAD123');
    const updatedAccount = await request('/api/account', 'GET', null, memberLogin.cookie);
    assert.equal(updatedAccount.data.orderHistory[0].status, 'SHIPPED'); assert.equal(updatedAccount.data.tickets[0].event, 'Test Run Edited'); assert.equal(updatedAccount.data.eventsAttended, 1);
    assert.equal(updatedAccount.data.orderHistory[0].notes, undefined);
    await request(`/api/admin/products/${product.data.id}`, 'DELETE');
    assert.equal((await request('/api/catalog')).data.products.some(item => item.id === product.data.id), false);
    assert.equal((await request(`/api/admin/orders/${order.data.id}`, 'PATCH', { status: 'CANCELLED' })).status, 200);
    assert.equal((await request(`/api/admin/products/${product.data.id}`, 'PATCH', { active: true })).data.archived, false);
    assert.equal((await request(`/api/admin/users/${createdUser.data.id}`, 'PATCH', { password: '456' })).status, 200);
    assert.equal((await request('/api/account', 'GET', null, memberLogin.cookie)).status, 401);
    assert.equal((await request('/api/signin', 'POST', { email: createdUser.data.email, password: '123' }, null)).status, 401);
    const resetLogin = await request('/api/signin', 'POST', { email: createdUser.data.email, password: '456' }, null); assert.equal(resetLogin.status, 200);
    await request(`/api/admin/users/${createdUser.data.id}`, 'PATCH', { status: 'DISABLED' });
    assert.equal((await request('/api/account', 'GET', null, resetLogin.cookie)).status, 401);
    assert.equal((await request('/api/signin', 'POST', { email: createdUser.data.email, password: '456' }, null)).status, 401);
    const saved = JSON.parse(await readFile(join(temporary, 'operations.json'), 'utf8'));
    assert.ok(saved.products.some(item => item.id === product.data.id)); assert.equal(saved.orders.find(item => item.id === order.data.id).status, 'CANCELLED');
    const savedAccounts = JSON.parse(await readFile(accountsFile, 'utf8')); assert.equal(savedAccounts.find(item => item.id === createdUser.data.id).password, undefined);
    await stop(); base = await start();
    assert.equal((await request('/api/admin/data')).status, 401);
    const again = await request('/api/signin', 'POST', { email: 'admin@radius.id', password: 'admin123' }, null); adminCookie = again.cookie;
    const persisted = await request('/api/admin/data'); assert.ok(persisted.data.products.some(item => item.id === product.data.id)); assert.equal(persisted.data.tickets.find(item => item.id === ticket.id).status, 'ATTENDED');
    assert.equal((await request('/api/admin/check-in', 'POST', scan)).status, 409);
    assert.equal(persisted.data.tickets.find(item => item.id === ticket.id).checkInToken, ticket.checkInToken);
    assert.equal((await fetch(base + imageUrl)).status, 200);
  } finally { await stop(); await rm(temporary, { recursive: true, force: true }); }
});
